#!/usr/bin/env python3
"""Deterministically decorate published prost definitions; never run protoc/downloads."""
import hashlib, json, pathlib, re, sys
ROOT = pathlib.Path(__file__).resolve().parent
def write(path, text):
    if '--check' in sys.argv:
        if path.read_text() != text: raise RuntimeError('generated source mismatch: '+str(path))
    else: path.write_text(text)
for name, digest in json.loads((ROOT/'vendor/SHA256.json').read_text()).items():
    if hashlib.sha256((ROOT/'vendor'/name).read_bytes()).hexdigest() != digest:
        raise RuntimeError('source hash mismatch: '+name)
source = '\n'.join((ROOT/'vendor'/n).read_text() for n in ['service.rs','compact_formats.rs'])
methods = [
 ('GetLatestBlock','ChainSpec','BlockId',False), ('GetLightdInfo','Empty','LightdInfo',False),
 ('GetTransaction','TxFilter','RawTransaction',False), ('GetAddressUtxos','GetAddressUtxosArg','GetAddressUtxosReplyList',False),
 ('GetTaddressBalance','AddressList','Balance',False), ('GetTreeState','BlockId','TreeState',False),
 ('SendTransaction','RawTransaction','SendResponse',False), ('GetSubtreeRoots','GetSubtreeRootsArg','SubtreeRoot',True),
 ('GetBlockRange','BlockRange','CompactBlock',True), ('GetTaddressTransactions','TransparentAddressBlockFilter','RawTransaction',True),
 ('GetMempoolStream','Empty','RawTransaction',True)]
structs = {}
for m in re.finditer(r'#\[derive\([^\n]+::prost::Message\)\]\npub struct (\w+) \{[^}]*\}', source): structs[m[1]]=m[0]
fields={}
for name,s in structs.items():
 fields[name]=[]
 for attrs,field,typ in re.findall(r'#\[prost\(([^\n]+)\)\]\n    pub (\w+): ([^\n]+),',s):
  kind=attrs.split(',')[0]; kind=kind.split(' = ')[0]; tag=int(re.search(r'tag = "(\d+)"',attrs)[1]); repeated='repeated' in attrs
  if kind=='message':kind=re.search(r'<(\w+)>',typ)[1]
  if kind=='enumeration':kind='int32'
  fields[name].append((tag,field,kind,repeated))
needed=set(x for m in methods for x in m[1:3]); todo=list(needed)
while todo:
 for _,_,kind,_ in fields[todo.pop()]:
  if kind in structs and kind not in needed: needed.add(kind);todo.append(kind)
out=['// @generated by generate.py from verified published prost definitions.']
for name in sorted(needed):
 s=structs[name].replace('::prost::Message)', '::prost::Message, serde::Serialize, serde::Deserialize)')
 s=s.replace('pub struct ', '#[serde(default, deny_unknown_fields)]\npub struct ')
 for _,f,k,r in fields[name]:
  if k in ['bytes','uint64','int64']:
   module={'bytes':'hex_bytes','uint64':'decimal_u64','int64':'decimal_i64'}[k]
   s=s.replace('    pub '+f+':','    #[serde(with = "crate::'+module+'") ]\n    pub '+f+':')
 out.append(s)
for name in ['PoolType','ShieldedProtocol']:
 m=re.search(r'#\[derive\([^\n]+::prost::Enumeration\)\]\n#\[repr\(i32\)\]\npub enum '+name+r' \{[^}]+\}',source);out.append(m[0])
write(ROOT/'src/messages.rs', '\n'.join(out)+'\n')
schema=['// @generated by generate.py.', 'pub fn fields(name: &str) -> &\'static [Field] { match name {']
for name in sorted(needed):
 schema.append('"'+name+'" => &['+','.join('Field { tag: %d, name: "%s", kind: "%s", repeated: %s }'%(t,f,k,str(r).lower()) for t,f,k,r in fields[name])+'],')
schema+=['_ => &[], }}']
write(ROOT/'src/schema.rs', '\n'.join(schema)+'\n')
# Method mapping is explicit and source-checked; no aliases or wire reflection.
dispatch=['// @generated by generate.py.', 'fn dispatch(method: &str, input: Input) -> Result<Output, String> { match method {']
for method,req,res,stream in methods:
 dispatch.append('"%s" => route::<messages::%s, messages::%s>(input, "%s", "%s", %s),'%(method,req,res,req,res,str(stream).lower()))
dispatch+=['_ => Err("unknown method".into()), }}']
write(ROOT/'src/dispatch.rs', '\n'.join(dispatch)+'\n')
write(ROOT/'tests/methods.json', json.dumps(methods,indent=2)+'\n')
