// @generated by cargo xtask generate.
fn dispatch(method: &str, input: Input) -> Result<Output, String> { match method {
"GetLatestBlock" => route::<messages::ChainSpec, messages::BlockId>(input, "ChainSpec", "BlockId", false),
"GetLightdInfo" => route::<messages::Empty, messages::LightdInfo>(input, "Empty", "LightdInfo", false),
"GetTransaction" => route::<messages::TxFilter, messages::RawTransaction>(input, "TxFilter", "RawTransaction", false),
"GetAddressUtxos" => route::<messages::GetAddressUtxosArg, messages::GetAddressUtxosReplyList>(input, "GetAddressUtxosArg", "GetAddressUtxosReplyList", false),
"GetTaddressBalance" => route::<messages::AddressList, messages::Balance>(input, "AddressList", "Balance", false),
"GetTreeState" => route::<messages::BlockId, messages::TreeState>(input, "BlockId", "TreeState", false),
"SendTransaction" => route::<messages::RawTransaction, messages::SendResponse>(input, "RawTransaction", "SendResponse", false),
"GetSubtreeRoots" => route::<messages::GetSubtreeRootsArg, messages::SubtreeRoot>(input, "GetSubtreeRootsArg", "SubtreeRoot", true),
"GetBlockRange" => route::<messages::BlockRange, messages::CompactBlock>(input, "BlockRange", "CompactBlock", true),
"GetTaddressTransactions" => route::<messages::TransparentAddressBlockFilter, messages::RawTransaction>(input, "TransparentAddressBlockFilter", "RawTransaction", true),
"GetMempoolStream" => route::<messages::Empty, messages::RawTransaction>(input, "Empty", "RawTransaction", true),
_ => Err("unknown method".into()), }}
