// @generated by generate.py from verified published prost definitions.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message, serde::Serialize, serde::Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct AddressList {
    #[prost(string, repeated, tag = "1")]
    pub addresses: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message, serde::Serialize, serde::Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct Balance {
    #[prost(int64, tag = "1")]
    #[serde(with = "crate::decimal_i64") ]
    pub value_zat: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message, serde::Serialize, serde::Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct BlockId {
    #[prost(uint64, tag = "1")]
    #[serde(with = "crate::decimal_u64") ]
    pub height: u64,
    #[prost(bytes = "vec", tag = "2")]
    #[serde(with = "crate::hex_bytes") ]
    pub hash: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message, serde::Serialize, serde::Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct BlockRange {
    #[prost(message, optional, tag = "1")]
    pub start: ::core::option::Option<BlockId>,
    #[prost(message, optional, tag = "2")]
    pub end: ::core::option::Option<BlockId>,
    #[prost(enumeration = "PoolType", repeated, tag = "3")]
    pub pool_types: ::prost::alloc::vec::Vec<i32>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message, serde::Serialize, serde::Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct ChainMetadata {
    /// the size of the Sapling note commitment tree as of the end of this block
    #[prost(uint32, tag = "1")]
    pub sapling_commitment_tree_size: u32,
    /// the size of the Orchard note commitment tree as of the end of this block
    #[prost(uint32, tag = "2")]
    pub orchard_commitment_tree_size: u32,
    /// the size of the Ironwood note commitment tree as of the end of this block
    #[prost(uint32, tag = "3")]
    pub ironwood_commitment_tree_size: u32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message, serde::Serialize, serde::Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct ChainSpec {}
#[derive(Clone, PartialEq, ::prost::Message, serde::Serialize, serde::Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct CompactBlock {
    /// the height of this block
    #[prost(uint64, tag = "2")]
    #[serde(with = "crate::decimal_u64") ]
    pub height: u64,
    /// if present, the ID (hash) of this block
    #[prost(bytes = "vec", tag = "3")]
    #[serde(with = "crate::hex_bytes") ]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    /// if present, the ID (hash) of this block's predecessor
    #[prost(bytes = "vec", tag = "4")]
    #[serde(with = "crate::hex_bytes") ]
    pub prev_hash: ::prost::alloc::vec::Vec<u8>,
    /// if non-zero, Unix epoch time when the block was mined
    #[prost(uint32, tag = "5")]
    pub time: u32,
    /// if present, full header (as returned by the getblock RPC)
    #[prost(bytes = "vec", tag = "6")]
    #[serde(with = "crate::hex_bytes") ]
    pub header: ::prost::alloc::vec::Vec<u8>,
    /// zero or more compact transactions from this block
    #[prost(message, repeated, tag = "7")]
    pub vtx: ::prost::alloc::vec::Vec<CompactTx>,
    /// information about the state of the chain as of this block
    #[prost(message, optional, tag = "8")]
    pub chain_metadata: ::core::option::Option<ChainMetadata>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message, serde::Serialize, serde::Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct CompactOrchardAction {
    /// \[32\] The nullifier of the input note
    #[prost(bytes = "vec", tag = "1")]
    #[serde(with = "crate::hex_bytes") ]
    pub nullifier: ::prost::alloc::vec::Vec<u8>,
    /// \[32\] The x-coordinate of the note commitment for the output note
    #[prost(bytes = "vec", tag = "2")]
    #[serde(with = "crate::hex_bytes") ]
    pub cmx: ::prost::alloc::vec::Vec<u8>,
    /// \[32\] An encoding of an ephemeral Pallas public key
    #[prost(bytes = "vec", tag = "3")]
    #[serde(with = "crate::hex_bytes") ]
    pub ephemeral_key: ::prost::alloc::vec::Vec<u8>,
    /// \[52\] The first 52 bytes of the encCiphertext field
    #[prost(bytes = "vec", tag = "4")]
    #[serde(with = "crate::hex_bytes") ]
    pub ciphertext: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message, serde::Serialize, serde::Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct CompactSaplingOutput {
    /// Note commitment u-coordinate.
    #[prost(bytes = "vec", tag = "1")]
    #[serde(with = "crate::hex_bytes") ]
    pub cmu: ::prost::alloc::vec::Vec<u8>,
    /// Ephemeral public key.
    #[prost(bytes = "vec", tag = "2")]
    #[serde(with = "crate::hex_bytes") ]
    pub ephemeral_key: ::prost::alloc::vec::Vec<u8>,
    /// First 52 bytes of ciphertext.
    #[prost(bytes = "vec", tag = "3")]
    #[serde(with = "crate::hex_bytes") ]
    pub ciphertext: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message, serde::Serialize, serde::Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct CompactSaplingSpend {
    /// Nullifier (see the Zcash protocol specification)
    #[prost(bytes = "vec", tag = "1")]
    #[serde(with = "crate::hex_bytes") ]
    pub nf: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message, serde::Serialize, serde::Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct CompactTx {
    /// The index of the transaction within the block.
    #[prost(uint64, tag = "1")]
    #[serde(with = "crate::decimal_u64") ]
    pub index: u64,
    /// The id of the transaction as defined in
    /// [§ 7.1.1 ‘Transaction Identifiers’](<https://zips.z.cash/protocol/protocol.pdf#txnidentifiers>)
    /// This byte array MUST be in protocol order and MUST NOT be reversed
    /// or hex-encoded; the byte-reversed and hex-encoded representation is
    /// exclusively a textual representation of a txid.
    #[prost(bytes = "vec", tag = "2")]
    #[serde(with = "crate::hex_bytes") ]
    pub txid: ::prost::alloc::vec::Vec<u8>,
    /// The transaction fee: present if server can provide. In the case of a
    /// stateless server and a transaction with transparent inputs, this will be
    /// unset because the calculation requires reference to prior transactions.
    /// If there are no transparent inputs, the fee will be calculable as:
    ///     valueBalanceSapling + valueBalanceOrchard + valueBalanceIronwood
    ///     + sum(vPubNew) - sum(vPubOld) - sum(tOut)
    #[prost(uint32, tag = "3")]
    pub fee: u32,
    #[prost(message, repeated, tag = "4")]
    pub spends: ::prost::alloc::vec::Vec<CompactSaplingSpend>,
    #[prost(message, repeated, tag = "5")]
    pub outputs: ::prost::alloc::vec::Vec<CompactSaplingOutput>,
    #[prost(message, repeated, tag = "6")]
    pub actions: ::prost::alloc::vec::Vec<CompactOrchardAction>,
    #[prost(message, repeated, tag = "9")]
    pub ironwood_actions: ::prost::alloc::vec::Vec<CompactOrchardAction>,
    /// `CompactTxIn` values corresponding to the `vin` entries of the full transaction.
    ///
    /// Note: the single null-outpoint input for coinbase transactions is omitted. Light
    /// clients can test `CompactTx.index == 0` to determine whether a `CompactTx`
    /// represents a coinbase transaction, as the coinbase transaction is always the
    /// first transaction in any block.
    #[prost(message, repeated, tag = "7")]
    pub vin: ::prost::alloc::vec::Vec<CompactTxIn>,
    /// A sequence of transparent outputs being created by the transaction.
    #[prost(message, repeated, tag = "8")]
    pub vout: ::prost::alloc::vec::Vec<TxOut>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message, serde::Serialize, serde::Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct CompactTxIn {
    /// The id of the transaction that generated the output being spent. This
    /// byte array must be in protocol order and MUST NOT be reversed or
    /// hex-encoded.
    #[prost(bytes = "vec", tag = "1")]
    #[serde(with = "crate::hex_bytes") ]
    pub prevout_txid: ::prost::alloc::vec::Vec<u8>,
    /// The index of the output being spent in the `vout` array of the
    /// transaction referred to by `prevoutTxid`.
    #[prost(uint32, tag = "2")]
    pub prevout_index: u32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message, serde::Serialize, serde::Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct Empty {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message, serde::Serialize, serde::Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct GetAddressUtxosArg {
    #[prost(string, repeated, tag = "1")]
    pub addresses: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(uint64, tag = "2")]
    #[serde(with = "crate::decimal_u64") ]
    pub start_height: u64,
    /// zero means unlimited
    #[prost(uint32, tag = "3")]
    pub max_entries: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message, serde::Serialize, serde::Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct GetAddressUtxosReply {
    #[prost(string, tag = "6")]
    pub address: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "1")]
    #[serde(with = "crate::hex_bytes") ]
    pub txid: ::prost::alloc::vec::Vec<u8>,
    #[prost(int32, tag = "2")]
    pub index: i32,
    #[prost(bytes = "vec", tag = "3")]
    #[serde(with = "crate::hex_bytes") ]
    pub script: ::prost::alloc::vec::Vec<u8>,
    #[prost(int64, tag = "4")]
    #[serde(with = "crate::decimal_i64") ]
    pub value_zat: i64,
    #[prost(uint64, tag = "5")]
    #[serde(with = "crate::decimal_u64") ]
    pub height: u64,
}
#[derive(Clone, PartialEq, ::prost::Message, serde::Serialize, serde::Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct GetAddressUtxosReplyList {
    #[prost(message, repeated, tag = "1")]
    pub address_utxos: ::prost::alloc::vec::Vec<GetAddressUtxosReply>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message, serde::Serialize, serde::Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct GetSubtreeRootsArg {
    /// Index identifying where to start returning subtree roots
    #[prost(uint32, tag = "1")]
    pub start_index: u32,
    /// Shielded protocol to return subtree roots for
    #[prost(enumeration = "ShieldedProtocol", tag = "2")]
    pub shielded_protocol: i32,
    /// Maximum number of entries to return, or 0 for all entries.
    #[prost(uint32, tag = "3")]
    pub max_entries: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message, serde::Serialize, serde::Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct LightdInfo {
    #[prost(string, tag = "1")]
    pub version: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub vendor: ::prost::alloc::string::String,
    /// true
    #[prost(bool, tag = "3")]
    pub taddr_support: bool,
    /// either "main" or "test"
    #[prost(string, tag = "4")]
    pub chain_name: ::prost::alloc::string::String,
    /// depends on mainnet or testnet
    #[prost(uint64, tag = "5")]
    #[serde(with = "crate::decimal_u64") ]
    pub sapling_activation_height: u64,
    /// protocol identifier, see consensus/upgrades.cpp
    #[prost(string, tag = "6")]
    pub consensus_branch_id: ::prost::alloc::string::String,
    /// latest block on the best chain
    #[prost(uint64, tag = "7")]
    #[serde(with = "crate::decimal_u64") ]
    pub block_height: u64,
    #[prost(string, tag = "8")]
    pub git_commit: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub branch: ::prost::alloc::string::String,
    #[prost(string, tag = "10")]
    pub build_date: ::prost::alloc::string::String,
    #[prost(string, tag = "11")]
    pub build_user: ::prost::alloc::string::String,
    /// less than tip height if zcashd is syncing
    #[prost(uint64, tag = "12")]
    #[serde(with = "crate::decimal_u64") ]
    pub estimated_height: u64,
    /// example: "v4.1.1-877212414"
    #[prost(string, tag = "13")]
    pub zcashd_build: ::prost::alloc::string::String,
    /// example: "/MagicBean:4.1.1/"
    #[prost(string, tag = "14")]
    pub zcashd_subversion: ::prost::alloc::string::String,
    /// Zcash donation UA address
    #[prost(string, tag = "15")]
    pub donation_address: ::prost::alloc::string::String,
    /// name of next pending network upgrade, empty if none scheduled
    #[prost(string, tag = "16")]
    pub upgrade_name: ::prost::alloc::string::String,
    /// height of next pending upgrade, zero if none is scheduled
    #[prost(uint64, tag = "17")]
    #[serde(with = "crate::decimal_u64") ]
    pub upgrade_height: u64,
    /// version of <https://github.com/zcash/lightwallet-protocol> served by this server
    #[prost(string, tag = "18")]
    pub lightwallet_protocol_version: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message, serde::Serialize, serde::Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct RawTransaction {
    /// The serialized representation of the Zcash transaction.
    #[prost(bytes = "vec", tag = "1")]
    #[serde(with = "crate::hex_bytes") ]
    pub data: ::prost::alloc::vec::Vec<u8>,
    /// The height at which the transaction is mined, or a sentinel value.
    ///
    /// Due to an error in the original protobuf definition, it is necessary to
    /// reinterpret the result of the `getrawtransaction` RPC call. Zcashd will
    /// return the int64 value `-1` for the height of transactions that appear
    /// in the block index, but which are not mined in the main chain. Here, the
    /// height field of `RawTransaction` was erroneously created as a `uint64`,
    /// and as such we must map the response from the zcashd RPC API to be
    /// representable within this space. Additionally, the `height` field will
    /// be absent for transactions in the mempool, resulting in the default
    /// value of `0` being set. Therefore, the meanings of the `height` field of
    /// the `RawTransaction` type are as follows:
    ///
    /// * height 0: the transaction is in the mempool
    /// * height 0xffffffffffffffff: the transaction has been mined on a fork that
    ///    is not currently the main chain
    /// * any other height: the transaction has been mined in the main chain at the
    ///    given height
    #[prost(uint64, tag = "2")]
    #[serde(with = "crate::decimal_u64") ]
    pub height: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message, serde::Serialize, serde::Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct SendResponse {
    #[prost(int32, tag = "1")]
    pub error_code: i32,
    #[prost(string, tag = "2")]
    pub error_message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message, serde::Serialize, serde::Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct SubtreeRoot {
    /// The 32-byte Merkle root of the subtree.
    #[prost(bytes = "vec", tag = "2")]
    #[serde(with = "crate::hex_bytes") ]
    pub root_hash: ::prost::alloc::vec::Vec<u8>,
    /// The hash of the block that completed this subtree.
    #[prost(bytes = "vec", tag = "3")]
    #[serde(with = "crate::hex_bytes") ]
    pub completing_block_hash: ::prost::alloc::vec::Vec<u8>,
    /// The height of the block that completed this subtree in the main chain.
    #[prost(uint64, tag = "4")]
    #[serde(with = "crate::decimal_u64") ]
    pub completing_block_height: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message, serde::Serialize, serde::Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct TransparentAddressBlockFilter {
    /// t-address
    #[prost(string, tag = "1")]
    pub address: ::prost::alloc::string::String,
    /// start, end heights only
    #[prost(message, optional, tag = "2")]
    pub range: ::core::option::Option<BlockRange>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message, serde::Serialize, serde::Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct TreeState {
    /// "main" or "test"
    #[prost(string, tag = "1")]
    pub network: ::prost::alloc::string::String,
    /// block height
    #[prost(uint64, tag = "2")]
    #[serde(with = "crate::decimal_u64") ]
    pub height: u64,
    /// block id
    #[prost(string, tag = "3")]
    pub hash: ::prost::alloc::string::String,
    /// Unix epoch time when the block was mined
    #[prost(uint32, tag = "4")]
    pub time: u32,
    /// sapling commitment tree state
    #[prost(string, tag = "5")]
    pub sapling_tree: ::prost::alloc::string::String,
    /// orchard commitment tree state
    #[prost(string, tag = "6")]
    pub orchard_tree: ::prost::alloc::string::String,
    /// ironwood commitment tree state
    #[prost(string, tag = "7")]
    pub ironwood_tree: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message, serde::Serialize, serde::Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct TxFilter {
    /// block identifier, height or hash
    #[prost(message, optional, tag = "1")]
    pub block: ::core::option::Option<BlockId>,
    /// index within the block
    #[prost(uint64, tag = "2")]
    #[serde(with = "crate::decimal_u64") ]
    pub index: u64,
    /// transaction ID (hash, txid)
    #[prost(bytes = "vec", tag = "3")]
    #[serde(with = "crate::hex_bytes") ]
    pub hash: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message, serde::Serialize, serde::Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct TxOut {
    /// The value of the output, in Zatoshis.
    #[prost(uint64, tag = "1")]
    #[serde(with = "crate::decimal_u64") ]
    pub value: u64,
    /// The script pubkey that must be satisfied in order to spend this output.
    #[prost(bytes = "vec", tag = "2")]
    #[serde(with = "crate::hex_bytes") ]
    pub script_pub_key: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PoolType {
    Invalid = 0,
    Transparent = 1,
    Sapling = 2,
    Orchard = 3,
    Ironwood = 4,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ShieldedProtocol {
    Sapling = 0,
    Orchard = 1,
    Ironwood = 2,
}
