use crate::support::{json, sha, Result};
use regex::Regex;
use std::{
    collections::{BTreeMap, BTreeSet},
    fs,
    path::Path,
};

const METHODS: &[(&str, &str, &str, bool)] = &[
    ("GetLatestBlock", "ChainSpec", "BlockId", false),
    ("GetLightdInfo", "Empty", "LightdInfo", false),
    ("GetTransaction", "TxFilter", "RawTransaction", false),
    (
        "GetAddressUtxos",
        "GetAddressUtxosArg",
        "GetAddressUtxosReplyList",
        false,
    ),
    ("GetTaddressBalance", "AddressList", "Balance", false),
    ("GetTreeState", "BlockId", "TreeState", false),
    ("SendTransaction", "RawTransaction", "SendResponse", false),
    ("GetSubtreeRoots", "GetSubtreeRootsArg", "SubtreeRoot", true),
    ("GetBlockRange", "BlockRange", "CompactBlock", true),
    (
        "GetTaddressTransactions",
        "TransparentAddressBlockFilter",
        "RawTransaction",
        true,
    ),
    ("GetMempoolStream", "Empty", "RawTransaction", true),
];

struct Field {
    tag: u32,
    name: String,
    kind: String,
    repeated: bool,
}

pub fn generate(root: &Path, check: bool) -> Result<()> {
    let root = root.join("lightwire");
    for (name, hash) in json(&root.join("vendor/SHA256.json"))?
        .as_object()
        .ok_or("invalid vendor hashes")?
    {
        if sha(&root.join("vendor").join(name))? != hash.as_str().ok_or("invalid vendor hash")? {
            return Err(format!("source hash mismatch: {name}").into());
        }
    }
    let source = fs::read_to_string(root.join("vendor/service.rs"))?
        + "\n"
        + &fs::read_to_string(root.join("vendor/compact_formats.rs"))?;
    let structs = Regex::new(r"#\[derive\([^\n]+::prost::Message\)\]\npub struct (\w+) \{[^}]*\}")?;
    let fields = Regex::new(r"#\[prost\(([^\n]+)\)\]\n    pub (\w+): ([^\n]+),")?;
    let tag = Regex::new("tag = \"(\\d+)\"")?;
    let message_type = Regex::new(r"<(\w+)>")?;
    let mut definitions = BTreeMap::new();
    let mut descriptors = BTreeMap::new();
    for definition in structs.captures_iter(&source) {
        let mut parsed = Vec::new();
        for field in fields.captures_iter(&definition[0]) {
            let attrs = &field[1];
            let mut kind = attrs
                .split(',')
                .next()
                .unwrap()
                .split(" = ")
                .next()
                .unwrap()
                .to_owned();
            if kind == "message" {
                kind = message_type
                    .captures(&field[3])
                    .ok_or("missing message type")?[1]
                    .into();
            }
            if kind == "enumeration" {
                kind = "int32".into();
            }
            parsed.push(Field {
                tag: tag.captures(attrs).ok_or("missing prost tag")?[1].parse()?,
                name: field[2].into(),
                kind,
                repeated: attrs.contains("repeated"),
            });
        }
        definitions.insert(definition[1].to_owned(), definition[0].to_owned());
        descriptors.insert(definition[1].to_owned(), parsed);
    }
    let mut needed: BTreeSet<String> = METHODS
        .iter()
        .flat_map(|(_, request, response, _)| [request.to_string(), response.to_string()])
        .collect();
    let mut todo: Vec<_> = needed.iter().cloned().collect();
    while let Some(name) = todo.pop() {
        for field in descriptors
            .get(&name)
            .ok_or_else(|| format!("missing message: {name}"))?
        {
            if definitions.contains_key(&field.kind) && needed.insert(field.kind.clone()) {
                todo.push(field.kind.clone());
            }
        }
    }
    let mut messages = vec![
        "// @generated by cargo xtask generate from verified published prost definitions."
            .to_owned(),
    ];
    let mut schema = vec![
        "// @generated by cargo xtask generate.".to_owned(),
        "pub fn fields(name: &str) -> &'static [Field] { match name {".into(),
    ];
    for name in needed {
        let mut definition = definitions[&name]
            .replace(
                "::prost::Message)",
                "::prost::Message, serde::Serialize, serde::Deserialize)",
            )
            .replace(
                "pub struct ",
                "#[serde(default, deny_unknown_fields)]\npub struct ",
            );
        let mut entries = Vec::new();
        for field in &descriptors[&name] {
            let module = match field.kind.as_str() {
                "bytes" => Some("hex_bytes"),
                "uint64" => Some("decimal_u64"),
                "int64" => Some("decimal_i64"),
                _ => None,
            };
            if let Some(module) = module {
                definition = definition.replace(
                    &format!("    pub {}:", field.name),
                    &format!(
                        "    #[serde(with = \"crate::{module}\") ]\n    pub {}:",
                        field.name
                    ),
                );
            }
            entries.push(format!(
                "Field {{ tag: {}, name: \"{}\", kind: \"{}\", repeated: {} }}",
                field.tag, field.name, field.kind, field.repeated
            ));
        }
        messages.push(definition);
        schema.push(format!("\"{name}\" => &[{}],", entries.join(",")));
    }
    for name in ["PoolType", "ShieldedProtocol"] {
        let pattern = Regex::new(&format!(
            r"#\[derive\([^\n]+::prost::Enumeration\)\]\n#\[repr\(i32\)\]\npub enum {name} \{{[^}}]+\}}"
        ))?;
        messages.push(pattern.find(&source).ok_or("missing enum")?.as_str().into());
    }
    schema.push("_ => &[], }}".into());
    let mut dispatch = vec![
        "// @generated by cargo xtask generate.".to_owned(),
        "fn dispatch(method: &str, input: Input) -> Result<Output, String> { match method {".into(),
    ];
    for (method, request, response, stream) in METHODS {
        dispatch.push(format!(
            "\"{method}\" => route::<messages::{request}, messages::{response}>\
             (input, \"{request}\", \"{response}\", {stream}),"
        ));
    }
    dispatch.push("_ => Err(\"unknown method\".into()), }}".into());
    for (path, content) in [
        ("src/messages.rs", messages.join("\n")),
        ("src/schema.rs", schema.join("\n")),
        ("src/dispatch.rs", dispatch.join("\n")),
        ("tests/methods.json", serde_json::to_string_pretty(METHODS)?),
    ] {
        let path = root.join(path);
        let content = content + "\n";
        if check {
            if fs::read_to_string(&path)? != content {
                return Err(format!("generated source mismatch: {}", path.display()).into());
            }
        } else {
            fs::write(path, content)?;
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    #[test]
    fn committed_output_matches_verified_definitions() {
        super::generate(
            Path::new(env!("CARGO_MANIFEST_DIR")).parent().unwrap(),
            true,
        )
        .unwrap();
    }
    use std::path::Path;
}
